FROM node:14 AS build-env
WORKDIR /weather

COPY . /weather
RUN npm install
RUN npm run build

FROM node:14 AS run-env
WORKDIR /app
COPY --from=build-env  /weather/build /app
RUN npm install -g serve
EXPOSE 5000
CMD ["serve", "-s"]