FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /weather
COPY . .
RUN dotnet publish -o /weather/out

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS run-env
WORKDIR /weather/app
COPY --from=build-env /weather/out /weather/app
ENV ASPNETCORE_URLS=http://+:5001 
CMD ["dotnet", "Weather.dll"]